require('preferences')
require('plugins')
require('settings')
require('file_tree')
require('treesitter')
require('language_servers')
require('_compe')
require('terminal')
require('which_key')
require('_telescope')
require('_gitsigns')
require('_galaxyline')
require('rooter')
require('_colorizer')
require('nvim_gps')

require('theme')
