require('preferences')
require('plugins')
require('settings')
require('dev-icons')
require('file_tree')
require('treesitter')
require('treesitter_textobjects')
require('plugin_configs.cmp')
require('terminal')
require('which_key')
require('plugin_configs.telescope')
require('_gitsigns')
require('plugin_configs.galaxyline')
require('plugin_configs.colorizer')
require('plugin_configs.navic')

require('plugin_configs.cosmic')
require('notifications')

require('theme')
require('plugin_configs.neotest')

require("plugin_configs.auto_session")

require('_mason')
require('plugin_configs.trouble')
require('plugin_configs.debugger')
require('plugin_configs.octo')
