require('preferences')
require('plugins')
require('settings')
require('file_tree')
require('treesitter')
require('treesitter_textobjects')
require('language_servers')
require('_compe')
require('terminal')
require('which_key')
require('_telescope')
require('_gitsigns')
require('_galaxyline')
-- require('rooter') # Migrate to https://github.com/ahmedkhalf/project.nvim
require('_colorizer')
require('nvim_gps')
-- require('comments')

require('cosmic')
require('notifications')

require('theme')
require('ultest')

require("auto_session")
